spring:
  application:
    name: mini-app
  datasource:
    url: jdbc:postgresql://telegram-app-bd-daniilyuk.db-msk0.amvera.tech:5432/telegram-app
    username: telegram-app
    password: telegram-app
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
